version: '3.2'
services:
  kafka:
    image: wurstmeister/kafka:latest
    hostname: "{{.Service.Name}}-{{.Task.Slot}}-test"
    dns: 
      - 192.168.99.30
    deploy:
      mode: replicated
      replicas: 3
    ports:
      - target: 9094
        published: 9094
        protocol: tcp
        mode: host
    environment:
      HOSTNAME_COMMAND: "hostname"      
      KAFKA_ZOOKEEPER_CONNECT: sbmvt-zk-test:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_PROTOCOL_NAME: OUTSIDE
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_PROTOCOL_NAME: INSIDE
      KAFKA_PORT: 9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    external:
      name: camp
